### ISSUE TITLE
Not compatible with eslint 8

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/eslint-plugin#2]
Just updated a project to latest eslint and seems this plugin is not compatible with it. Getting the following error:
```
Oops! Something went wrong! :(

ESLint: 8.13.0

TypeError: Failed to load plugin '@nativescript' declared in '--config': Class extends value undefined is not a constructor or null
Referenced from: /Users/peter/Projects/SwyftCG/.eslintrc.json
    at Object.<anonymous> (/Users/peter/Projects/SwyftCG/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/Users/peter/Projects/SwyftCG/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/peter/Projects/SwyftCG/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/peter/Projects/SwyftCG/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/Users/peter/Projects/SwyftCG/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
```

**Comment by sebj54** [comment]
@sis0k0 @NathanWalker Hey there, are you interested in any help for the eslint 8 migration? I could implement the changes, test the package and submit a ready-to-merge PR if you'd like

**Comment by SmailHammour** [comment]
@NathanWalker any plans on fixing this?

**Comment by hendrickson-tyler** [comment]
Adding my voice to the choir too. Would love to see this plugin maintained, I think some official ESLint rules are a great benefit to the NativeScript community.

@NathanWalker What can we do to help out with this?

**Comment by NathanWalker** [comment]
Hi @hendrickson-tyler thank you agreed. If a PR were posted to help resolve any current issue would be greatly alleviated and we could help get a major version published.
